#include <stdio.h>

/**
 * main - Fibonacci sequence is generated by adding the previous two terms
 *
 * Return: 0
 */

int main(void)
{
	int limit = 4000000;
	int term_1 = 1;
	int term_2 = 2;
	int next;
	int sum = 2;

	while (next <= limit)
	{
		next = term_1 + term_2;
		if (next % 2 == 0)
			sum = sum + next;
		term_1 = term_2;
		term_2 = next;
	}
	printf("%d\n", sum);
	return (0);
}
